name: Deploy ArgoCD to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Install kubectl
      run: |
        curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
    - name: Login into EKS cluster
      run: |
        aws eks --region us-east-1 update-kubeconfig --name metronetpocprometheus
    - name: Installing ArgoCD
      run: |
        kubectl get pods
    - name: Patching and Exposing the LoadBalancer URL
      run: |
        kubectl patch svc argocd-server -p '{"spec": {"type": "LoadBalancer"}}'
        kubectl get svc
        echo "ArgoCD is up and successfully installed over AWS Elastic Kubernetes Service..!!"
    - name: Fetching the ArgoCD Root Password
      run: |
        kubectl get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo
