name: CI
on:
  push:
    branches: [ "jenkins-trigger" ]
jobs:
  jenkins_job:
    name: building
    runs-on: ubuntu-latest
    steps:
    - name: Checkout App Code 
      uses: actions/checkout@master
    - name: Building jenkins_job
      env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          jenkins_url="http://ec2-3-16-151-254.us-east-2.compute.amazonaws.com:8080"
          jenkins_project="pipeline-07092022"
          user="pulkit_apisero"
          crumb=$(curl -u "pulkit_apisero:admin" -s '$jenkins_url/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
          echo $crumb
          curl -X POST -u $user:117e121e8bfab4b23e8bc8d9215ba316b7 $jenkins_url/job/$jenkins_project/build
          result=$(curl -X GET $jenkins_url/job/$jenkins_project/lastBuild/api/xml?xpath=concat(//personalstatus,":",//result))
          echo $result
          echo "Build Status is: $result"
